# Deployment configuration file. Beware when removing '#': indentation matters

image:
  # verify this is correct by opening the following URL in your browser
  # https://github.com/manole-alexandru/edu-ubb-gpu/pkgs/container/edu-ubb-gpu
  repository: ghcr.io/manole-alexandru/edu-ubb-gpu
  tag: latest  # change this value to the latest specific image tag in the repository

# customize the name of the Mlflow experiment
#experiment: edu-ubb-gpu-experiment

entrypoint:
  command:
    - "python"
    - "-m"
    - "edu_ubb_gpu"
  # configure command-line arguments
  # parameters are kebab-cased and prefixed with double dash before passing them
  # as command-line args
  # e.g. 'alpha' becomes '--alpha=<value>' 'l1Ratio' becomes '--l1-ratio=<value>'
  #parameters:
  #  - name: alpha
  #    value: 0.6
  #  - name: l1Ratio
  #    value: 0.1

# Configure storage options for the training data
#storage:
#  # either 'local' or 'minio' (default: 'local')
#  # if 'local', data must be preloaded in the container image
#  type: local
#
#  # MinIO training data storage configuration
#  minio:
#    # Minio to use (EduML: leave this as-is)
#    uri: "minio.minio.svc.cluster.local:80"
#    # credentials with access to an S3 bucket on Minio (EduML: leave this as-is)
#    credentials: "minio-access"
#    # S3 bucket name (EduML: configure to supplied value)
#    bucket: "test-bucket"
#    # path to training data, inside S3 bucket - no leading path separators
#    path: "data.csv"
